import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  gradientContainer: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    paddingTop: 60,
    paddingBottom: 24,
  },
  logoContainer: {
    width: 80,
    height: 80,
    backgroundColor: colors.white,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
    marginBottom: 16,
  },
  logoIcon: {
    width: 40,
    height: 40,
  },
  appTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.white,
    marginBottom: 4,
  },
  appSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 32,
    width: '100%',
    maxWidth: 393,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.25,
    shadowRadius: 50,
    elevation: 10,
    marginBottom: 40,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 16,
    color: colors.textGray,
    lineHeight: 24,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    color: colors.textGray,
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: 10,
    paddingHorizontal: 16,
  },
  inputIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
  },
  input: {
    flex: 1,
    height: 50,
    fontSize: 14,
    color: colors.textDark,
    paddingVertical: 0,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfWidth: {
    width: '48%',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  checkbox: {
    width: 16,
    height: 16,
    marginRight: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: colors.textGray,
    flex: 1,
  },
  footer: {
    marginTop: 24,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  footerText: {
    color: colors.textGray,
    fontSize: 16,
  },
  link: {
    color: colors.primary,
    fontWeight: '600',
    marginLeft: 4,
  },
  scanBox: {
    backgroundColor: 'rgba(21, 93, 252, 0.1)',
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: 10,
    padding: 16,
    marginBottom: 24,
    alignItems: 'center',
  },
  scanHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  scanIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  scanTitle: {
    fontSize: 16,
    color: colors.textDark,
    fontWeight: '500',
  },
  scanButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  scanButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '500',
  },
  scanHint: {
    fontSize: 12,
    color: colors.textLight,
  },
  // Login specific styles
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  loginLogoContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  loginLogoCircle: {
    width: 80,
    height: 80,
    backgroundColor: colors.white,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 16,
  },
  brandName: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.white,
    marginBottom: 4,
  },
  brandTagline: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  formOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 16,
  },
  rememberMe: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rememberMeText: {
    marginLeft: 8,
    fontSize: 14,
    color: colors.textGray,
  },
  forgotPassword: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },
  signupSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 24,
  },
  signupText: {
    fontSize: 14,
    color: colors.textGray,
  },
  moderatorSection: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.1)',
    paddingTop: 18,
    alignItems: 'center',
  },
  moderatorButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  moderatorButtonText: {
    marginLeft: 8,
    fontSize: 14,
    color: colors.textGray,
    fontWeight: '500',
  },
  errorText: {
    color: colors.error,
    fontSize: 12,
    marginTop: 4,
  },
});
